apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-deployment

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: ai-engine

  template:
    metadata:
      labels:
        app: ai-engine

    spec:
      containers:
        - name: ai-engine

          image: nikhil602/sentinelai-ai-engine:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8001

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"